default: cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/IShuffleList.java cpsc2150/listDec/ShuffleList.java
	javac cpsc2150/listDec/ShuffleApp.java cpsc2150/listDec/IShuffleList.java cpsc2150/listDec/ShuffleList.java

run: cpsc2150/listDec/IShuffleList.class cpsc2150/listDec/ShuffleList.class cpsc2150/listDec/ShuffleApp.class
	java cpsc2150/listDec/ShuffleApp

clean:
	rm cpsc2150/listDec/*.class
