default: cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageView.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/MortgageApp.java cpsc2150/mortgages/AbsCustomer.java cpsc2150/mortgages/AbsMortgage.java cpsc2150/mortgages/ICustomer.java cpsc2150/mortgages/Customer.java
	javac cpsc2150/mortgages/MortgageController.java cpsc2150/mortgages/IMortgageController.java cpsc2150/mortgages/IMortgageView.java cpsc2150/mortgages/MortgageView.java cpsc2150/mortgages/IMortgage.java cpsc2150/mortgages/Mortgage.java cpsc2150/mortgages/MortgageApp.java cpsc2150/mortgages/AbsCustomer.java cpsc2150/mortgages/AbsMortgage.java cpsc2150/mortgages/ICustomer.java cpsc2150/mortgages/Customer.java

run: cpsc2150/mortgages/MortgageController.class cpsc2150/mortgages/IMortgageController.class cpsc2150/mortgages/IMortgageView.class cpsc2150/mortgages/MortgageView.class cpsc2150/mortgages/IMortgage.class cpsc2150/mortgages/Mortgage.class cpsc2150/mortgages/MortgageApp.class cpsc2150/mortgages/AbsCustomer.class cpsc2150/mortgages/AbsMortgage.class cpsc2150/mortgages/ICustomer.class cpsc2150/mortgages/Customer.class
	java cpsc2150/mortgages/MortgageApp

clean:
	rm cpsc2150/mortgages/*.class
