default: cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/AbsQueue.java
	javac -Xlint:unchecked cpsc2150/MyQueue/QueueApp.java cpsc2150/MyQueue/ArrayQueue.java cpsc2150/MyQueue/IQueue.java cpsc2150/MyQueue/ListQueue.java cpsc2150/MyQueue/AbsQueue.java

run: cpsc2150/MyQueue/IQueue.class cpsc2150/MyQueue/ListQueue.class cpsc2150/MyQueue/ArrayQueue.class cpsc2150/MyQueue/QueueApp.class cpsc2150/MyQueue/AbsQueue.class
	java cpsc2150/MyQueue/QueueApp

clean:
	rm -f cpsc2150/MyQueue/*.class
